sudo: required
services:
  - docker

before_install:
  - docker build -t spoorthi54/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true spoorthi54/docker-react-test npm run test

after_success: 
  - docker build -t spoorthi54/multicont-proj-client  ./client
  - docker build -t spoorthi54/multicont-proj-nginx  ./nginx
  - docker build -t spoorthi54/multicont-proj-server  ./server
  - docker build -t spoorthi54/multicont-proj-worker  ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  #push into the docker hub
  - docker push spoorthi54/multicont-proj-client
  - docker push spoorthi54/multicont-proj-nginx
  - docker push spoorthi54/multicont-proj-server
  - docker push spoorthi54/multicont-proj-worker
